### ISSUE TITLE
部署新机器的时候突然发现不兼容修改

### ISSUE THREAD

**Issue by Yuzf-code** [walkor/redis-queue#5]
v1.0.3 - v1.0.9之间为什么会修改到队列名的前缀呢
由于使用队列和其他的系统进行了通信，底层的队列名前缀修改后相当于我只是升级了个版本，系统之间的通信却断了，当时定位了很久🤣
（PS：没有其他意思哈，因为没有太细追源码，比较好奇这个修改的初衷）

**Comment by walkor** [comment]
为了兼容redis集群
