### ISSUE TITLE
命名空间错误，需要更改成Workerman\lib\Timer

### ISSUE THREAD

**Issue by stepbyfeng** [walkor/redis-queue#6]
# 命名空间错误
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/19253469/188540923-e95c33a9-a2bc-4f43-a092-26454e3afdda.png">
"workerman/workerman": "^3.5"

**Comment by walkor** [comment]
这个命名空间不用了，请升级workerman

**Comment by stepbyfeng** [comment]
workerman用的3.5的 但是redis的client是错的

**Comment by stepbyfeng** [comment]
<img width="637" alt="image" src="https://user-images.githubusercontent.com/19253469/188541335-6813edab-aa96-4a80-b659-a938e5ff68a2.png">
在3.5调用他的时候timer命名空间不是lib，然后报错了

**Comment by walkor** [comment]
3.5 用 v1.0.6
composer require workerman/redis-queue v1.0.6

**Comment by stepbyfeng** [comment]
redis-queue 的引入了，但是redis的client还是没对。版本是v1.0.8

**Comment by stepbyfeng** [comment]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/19253469/188545129-af3d44fb-98b7-479c-83d0-ae85275b0cdf.png">

**Comment by walkor** [comment]
搞不定就改下源码吧，workerman 3.5 太老了，已经不维护了
